name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: prepare
        run: |
          sudo apt-get install googletest
          sudo apt-get install lcov
      - uses: actions/checkout@v2
      - name: build
        run: |
          mkdir build
          cd build
          cmake ..

