name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - use: actions/checkout@v2
      - name: build
        run: |
          mkdir build
          cd build
          cmake ..

