name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: prepare
        run: |
          sudo apt-get install googletest
          sudo apt-get install lcov
      - name: install gtest
        run: |
          cd /usr/src/googletest
          sudo cmake .
          sudo make
          sudo make install
          cd ~
      - uses: actions/checkout@v2
      - name: build
        run: |
          mkdir build
          cd build
          cmake ..
          cd ..
          make

